-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_LINEAGE AS (
    SELECT ID, PARENT_ID, 1 GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, EL.GENERATION + 1
    FROM ECOLI_DATA E
    INNER JOIN ECOLI_LINEAGE EL ON E.PARENT_ID = EL.ID
)
SELECT ID
FROM ECOLI_LINEAGE
WHERE GENERATION = 3
ORDER BY ID;