-- 코드를 입력하세요
WITH AVAILABLE_CARS AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    ) and (CAR_TYPE = 'SUV' or CAR_TYPE = '세단')
),
TOTAL_DISCOUNTED_FEE AS (
    SELECT c.CAR_ID, c.CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30) FEE
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE
    WHERE DURATION_TYPE = '30일 이상'
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM AVAILABLE_CARS
JOIN TOTAL_DISCOUNTED_FEE
USING (CAR_ID)
WHERE (FEE >= 500000 and FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
