-- 코드를 입력하세요
SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, m.FAVORITES
FROM REST_INFO r
JOIN
(
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) m
ON r.FOOD_TYPE = m.FOOD_TYPE and r.FAVORITES = m.FAVORITES
ORDER BY r.FOOD_TYPE DESC;