-- 코드를 작성해주세요
SELECT ID, IF(r <= CRITICAL, 'CRITICAL', 
              IF(r <= HIGH, 'HIGH', 
                 IF(r <= MEDIUM, 'MEDIUM', 'LOW'))) COLONY_NAME
FROM
(
    SELECT ID, ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) r
    FROM ECOLI_DATA
    ORDER BY ID
) ECOLI_RANK
JOIN
(
    SELECT COUNT(*) / 4 CRITICAL, COUNT(*) / 2 HIGH, COUNT(*) * 3 / 4 MEDIUM, COUNT(*) LOW
    FROM ECOLI_DATA
) RANK_NAME