-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i
INNER JOIN ANIMAL_OUTS o
ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE SEX_UPON_INTAKE like "Intact%" and (SEX_UPON_OUTCOME like "Spayed%" or SEX_UPON_OUTCOME like "Neutered%")
ORDER BY i.ANIMAL_ID
