-- 코드를 입력하세요
WITH REVIEW_BY_REST AS (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
)
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS,SCORE
FROM REST_INFO
JOIN REVIEW_BY_REST
USING(REST_ID)
WHERE ADDRESS like "서울%"
ORDER BY SCORE DESC, FAVORITES DESC;
