WITH USER_GENDER AS (
    SELECT USER_ID, GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
)
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT USER_ID) USERS
FROM ONLINE_SALE INNER JOIN USER_GENDER USING(USER_ID)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;