-- 코드를 입력하세요
WITH USER_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT USER_ID) PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_2021),1) PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT * FROM USER_2021
)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH