-- 코드를 작성해주세요
WITH RECURSIVE ECOLI_GENERATION AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    SELECT E.ID, EG.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_GENERATION EG
    ON E.PARENT_ID = EG.ID
)
SELECT COUNT(*) COUNT, GENERATION
FROM ECOLI_GENERATION
JOIN ECOLI_DATA p
USING(ID)
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA c
    WHERE p.ID = c.PARENT_ID
)
GROUP BY GENERATION
ORDER BY GENERATION
