-- 코드를 입력하세요
SELECT CAR_ID, IF(SUM(IF(DATEDIFF(END_DATE, "2022-10-16") >= 0 and DATEDIFF("2022-10-16", START_DATE) >= 0, 1, 0)) >= 1, "대여중", "대여 가능") AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;