-- 코드를 입력하세요
WITH FOOD_ORDER_BY_PRODUCT AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) SUM
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
)
SELECT PRODUCT_ID, PRODUCT_NAME, SUM * PRICE TOTAL_SALES
FROM FOOD_ORDER_BY_PRODUCT
JOIN FOOD_PRODUCT
USING(PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID