-- 코드를 입력하세요
WITH CAR_RENTAL_HISTORY_WITH_DURATION_TYPE AS (
    SELECT HISTORY_ID, CAR_ID, RENT_DATE,
        CASE
            WHEN RENT_DATE < 7 THEN "해당 없음"
            WHEN RENT_DATE < 30 THEN "7일 이상"
            WHEN RENT_DATE < 90 THEN "30일 이상"
            ELSE "90일 이상"
        END DURATION_TYPE
    FROM (
        SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 RENT_DATE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) CAR_RENTAL_HISTORY_WITH_DATE
)
SELECT HISTORY_ID,IF(DISCOUNT_RATE IS NULL, DAILY_FEE * RENT_DATE,
                     ROUND((DAILY_FEE * (100 - DISCOUNT_RATE) / 100) * RENT_DATE)) FEE
FROM CAR_RENTAL_HISTORY_WITH_DURATION_TYPE
INNER JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING(CAR_TYPE, DURATION_TYPE)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC