-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, d.MCDP_CD, d.DR_NAME, APNT_YMD
FROM APPOINTMENT
JOIN PATIENT USING(PT_NO)
JOIN DOCTOR d ON DR_ID = MDDR_ID
WHERE DATEDIFF(APNT_YMD, '2022-04-13') = 0 AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;