-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
),
COUNT_FOR_HOUR AS (
    SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR
)
SELECT HOUR, IFNULL(COUNT, 0) COUNT
FROM COUNT_FOR_HOUR
RIGHT OUTER JOIN HOURS
USING(HOUR)