-- 코드를 작성해주세요
WITH FRONT_END_CODE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
FRONT_END_DEVELOPER AS (
    SELECT ID, COUNT(*) SKILL_COUNT
    FROM DEVELOPERS
    JOIN FRONT_END_CODE
    WHERE CODE & SKILL_CODE >= 1
    GROUP BY ID
    HAVING SKILL_COUNT >= 1
)
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (SELECT ID FROM FRONT_END_DEVELOPER)
ORDER BY ID;