-- 코드를 작성해주세요
WITH HR_GRADE_YEAR AS (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT EMP_NO, EMP_NAME,
    CASE
        WHEN SCORE >= 192 THEN 'S'
        WHEN SCORE >= 180 THEN 'A'
        WHEN SCORE >= 160 THEN 'B'
        ELSE 'C'
    END GRADE,
    CASE
        WHEN SCORE >= 192 THEN ROUND(SAL * 0.2)
        WHEN SCORE >= 180 THEN ROUND(SAL * 0.15)
        WHEN SCORE >= 160 THEN ROUND(SAL * 0.1)
        ELSE 0
    END BONUS
FROM HR_GRADE_YEAR
JOIN HR_EMPLOYEES
USING(EMP_NO)
ORDER BY EMP_NO