-- 코드를 입력하세요
WITH MAX_REVIEWER_ID AS (
    SELECT MEMBER_ID FROM (
    SELECT MEMBER_ID, COUNT(*) COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC) REVIEW_COUNT
    WHERE COUNT = (
        SELECT COUNT(*)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM REST_REVIEW
JOIN MEMBER_PROFILE
USING (MEMBER_ID)
WHERE MEMBER_ID IN (SELECT * FROM MAX_REVIEWER_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT;