-- 코드를 작성해주세요
SELECT my.ITEM_ID ITEM_ID, my.ITEM_NAME, my.RARITY
FROM ITEM_INFO my, ITEM_INFO p, ITEM_TREE t
WHERE p.RARITY = 'RARE' and p.ITEM_ID = t.PARENT_ITEM_ID and my.ITEM_ID = t.ITEM_ID
ORDER BY my.ITEM_ID DESC;
