-- 코드를 입력하세요
WITH SELECTED_CARS AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING SUM(IF(YEAR(START_DATE) = 2022 and MONTH(START_DATE) >= 8 and MONTH(START_DATE) <= 10, 1, 0)) >= 5
)
SELECT MONTH(START_DATE) MONTH, c.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
JOIN SELECTED_CARS s
ON c.CAR_ID = s.CAR_ID
WHERE YEAR(START_DATE) = 2022 and MONTH(START_DATE) >= 8 and MONTH(START_DATE) <= 10
GROUP BY MONTH, c.CAR_ID
ORDER BY MONTH, CAR_ID DESC