-- 코드를 작성해주세요
SELECT f1.ID, fn.FISH_NAME, f1.LENGTH
FROM FISH_INFO f1
JOIN
(
    SELECT FISH_TYPE, MAX(LENGTH) LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS fm
ON f1.FISH_TYPE = fm.FISH_TYPE and f1.LENGTH = fm.LENGTH
JOIN FISH_NAME_INFO fn
ON f1.FISH_TYPE = fn.FISH_TYPE
ORDER BY f1.ID