-- 코드를 입력하세요
WITH MAX_PRICE_BY_CATEGORY AS (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
JOIN MAX_PRICE_BY_CATEGORY
USING(CATEGORY)
WHERE CATEGORY IN ('과자','국','김치','식용유') AND PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC;