-- 코드를 작성해주세요
WITH FISH_INFO_WITHOUT_NULL as(
    SELECT ID, IFNULL(LENGTH, 10) LENGTH, FISH_TYPE
    FROM FISH_INFO
)
SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM FISH_INFO_WITHOUT_NULL
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE