-- 코드를 작성해주세요
WITH
FRONT_MASK AS (
    SELECT SUM(CODE) CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PYTHON_MASK AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
CS_MASK AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
)
SELECT IF(SKILL_CODE & (SELECT CODE FROM FRONT_MASK) >= 1 AND SKILL_CODE & (SELECT CODE FROM PYTHON_MASK) >= 1, 'A', IF(SKILL_CODE & (SELECT CODE FROM CS_MASK) >= 1, 'B','C')) GRADE, ID, EMAIL
FROM DEVELOPERS
WHERE (SKILL_CODE & (SELECT CODE FROM FRONT_MASK) >= 1 AND SKILL_CODE & (SELECT CODE FROM PYTHON_MASK) >= 1)
    OR (SKILL_CODE & (SELECT CODE FROM CS_MASK) >= 1) OR (SKILL_CODE & (SELECT CODE FROM FRONT_MASK) >= 1)
ORDER BY GRADE, ID