WITH MASKS AS (
    SELECT 
        SUM(IF(CATEGORY = 'Front End', CODE, 0)) AS FRONT,
        SUM(IF(NAME = 'Python', CODE, 0)) AS PYTHON,
        SUM(IF(NAME = 'C#', CODE, 0)) AS CS
    FROM SKILLCODES
)
SELECT 
    CASE
        WHEN (SKILL_CODE & FRONT) AND (SKILL_CODE & PYTHON) THEN 'A'
        WHEN (SKILL_CODE & CS) THEN 'B'
        WHEN (SKILL_CODE & FRONT) THEN 'C'
        END GRADE,
    ID, EMAIL
FROM DEVELOPERS, MASKS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID