name : generate Notion Page

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0' # 사용할 Node.js 버전

      - name: Install dependencies
        run: npm install axios fs puppeteer sharp dotenv
        
      - name: Get changed files
        id: get_changed_files
        run: |
          # 현재 커밋의 변경된 파일 목록을 가져옵니다.
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only HEAD~1 HEAD >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          CHANGED_FILES: ${{ env.CHANGED_FILES }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: node docs/createNotionPage.js # 실행할 Node.js 스크립트 경로
